### ISSUE TITLE
Create the mother of all contracts

### ISSUE THREAD

**Issue by athei** [use-ink/ink#1181]
It would be massively helpful for Ul development to create an example contract that uses as much functionality as possible. I mean that from an input/output standpoint:

* Use a lot of different complicated nested input and ouput types
* Use debug printing
* Use revert
* Use trap

This list is not exhaustive. The contract doesn't need to make sense. Just something that exercises the limits of the UI.

cc @statictype 

Would be a good issue for someone new.

**Comment by cmichi** [comment]
Once we have it, we should test if the `call`, `initiate`, etc. sub-commands of `cargo-contract` behave correctly with this contract.
