### ISSUE TITLE
E2E tests throw `custom attribute panicked` when under cargo workspace 

### ISSUE THREAD

**Issue by wottpal** [use-ink/ink#1672]
As first reported by @ganesh1233456 [here](https://github.com/scio-labs/inkathon/pull/14), and reproduced by me, when putting an e2e tested contract directory (e.g. https://github.com/paritytech/ink-examples/tree/main/flipper) under a `Cargo.toml` with a workspace definition:

```toml
[workspace]
members = ["flipper"]
```

The e2e test command fails and throws the following errors:

```
➜  flipper git:(develop) ✗ cargo test --features e2e-tests 
   Compiling flipper v4.0.0 (/Users/wottpal/Developer/scio-labs/inkathon/packages/contracts/flipper)
error: custom attribute panicked
  --> flipper/lib.rs:62:9
   |
62 |         #[ink_e2e::test]
   |         ^^^^^^^^^^^^^^^^
   |
   = help: message: contract build for Cargo.toml failed: Cannot infer the root project id

error: custom attribute panicked
  --> flipper/lib.rs:94:9
   |
94 |         #[ink_e2e::test]
   |         ^^^^^^^^^^^^^^^^
   |
   = help: message: Once instance has previously been poisoned

warning: unused import: `super::*`
  --> flipper/lib.rs:57:13
   |
57 |         use super::*;
   |             ^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `ink_e2e::build_message`
  --> flipper/lib.rs:58:13
   |
58 |         use ink_e2e::build_message;
   |             ^^^^^^^^^^^^^^^^^^^^^^

warning: `flipper` (lib test) generated 2 warnings
error: could not compile `flipper` due to 2 previous errors; 2 warnings emitted
```

Or are we missing something? Ty in advance!

**Comment by SkymanOne** [comment]
Can confirm the issue:

To reproduce:
1. Checkout https://github.com/paritytech/ink-examples
2. Create Cargo.toml in the root directory and put
```toml
[workspace]
members = ["flipper"]
```
3. run `cargo test --features e2e-tests` in the root directory

**Comment by armyhaylenko** [comment]
any updates here? :(

**Comment by wottpal** [comment]
we would also love to see this one fixed (preferably in the next ~2 weeks – but i know there are also a lot of other things that might need to be prioritized)..

**Comment by ascjones** [comment]
Please try with https://github.com/paritytech/ink/pull/1709

**Comment by armyhaylenko** [comment]
@ascjones the build seems to run fine except for this error: `cannot find type PolkadotConfig in crate ink_e2e`. any thoughts on what it might be?

**Comment by ascjones** [comment]
`PolakdotConfig` is under the `std` feature, which should be enabled by default. Do you have `default-features = false`?

**Comment by armyhaylenko** [comment]
it works!! thanks @ascjones ❤️
