### ISSUE TITLE
Using string type causes  ABI file  format Incorrect

### ISSUE THREAD

**Issue by jeremymj** [use-ink/ink#212]
I created a new contract using command  `cargo contract new envtest`,and added a new field to the  contract. ![Screenshot from 2019-10-18 17-40-55](https://user-images.githubusercontent.com/13585788/67087193-01adb480-f1d5-11e9-8b51-fefa693b1cde.png)
And create abi file using command `cargo  +nightly run -p abi-gen` , when I upload wasm file,UI shows that the abi file format is incorrect.
![Screenshot from 2019-10-18 17-53-02](https://user-images.githubusercontent.com/13585788/67087651-edb68280-f1d5-11e9-9ad7-0b082eced647.png)

**Comment by Robbepop** [comment]
Thank you for the bug report. Can you please paste the generated ABI file?

**Comment by jacogr** [comment]
cc @kwingram25 I believe this is probably mis-handled on the API layer. As soon as we have an ABI from @jeremymj could you please take a look?

**Comment by jeremymj** [comment]
@Robbepop This is the contract I created, using the command `cargo +nightly run -p abi-gen ` generated the abi file.[abi.txt](https://github.com/paritytech/ink/files/3746069/abi.txt).
I installed the ink! utility using Cargo with:
 `cargo install --force --git https://github.com/paritytech/ink cargo-contract`

**Comment by Robbepop** [comment]
@jeremymj Does this bug still exist or was it fixed in the meantime since there have been many changes in the API layer?

**Comment by kwingram25** [comment]
The issue was with an array/vector type, not strings. It should be fixed now

**Comment by Robbepop** [comment]
I ll close once @jeremymj approves this.

**Comment by jeremymj** [comment]
@Robbepop I have tested it with the `b748cc16a2ef66f579eb3d0ee2b1c718fe34a658` version of the ink, using the UI to upload abi.json without error, the contract can be `deploy` normally.

**Comment by Robbepop** [comment]
Thanks. Closed.
